#!/usr/bin/env bash
# Configures firewall

sudo apt-get update
sudo apt-get install ufw
sudo ufw enable
sudo ufw allow 22/tcp
sudo ufw allow 443/tcp
sudo ufw allow 80/tcp
sudo ufw default deny incoming
sudo ufw status numbered
